services:
  - type: web
    name: cloud-compare-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: FAST_MODE
        value: "1"
      - key: TAVILY_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
